import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

const tailwind_prefix = "storybook"+":";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={cn(`${tailwind_prefix}h-full`, `${tailwind_prefix}antialiased`, `${tailwind_prefix}font-sans`)}
        >
            <body
                className={cn(`${tailwind_prefix}min-h-full`, `${tailwind_prefix}flex`, `${tailwind_prefix}flex-col`)}>
                {children}
            </body>
        </html>
    );
}
